import "./bootstrap.min.js";
import "./jquery.min.js";
import "./jquery-migrate-1.2.1.min.js";
import "./slick.min.js";
import "./slider-home.js";
import "./home.js";
import "./accordion.js";
import "./tab.js";
import "./video.js";
