on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: tyrrrz/action-http-request@master
        with:
          url: https://flashpanel.io/api/servers/102961/sites/109207/deploy/http?token=MUFDNkE3MTctNUNFRi00RjU1LTg1N0ItNDhDNjM4MkI3NUYz
